---
title: "Monitoring Return to Substance Use with Personal Sensing"
subtitle: "Capstone Presentation"
author: "Kendra Wyant"
date: "April 26, 2024"
institute: "University of Wisconsin-Madison"
format: 
  revealjs:
    scrollable: true
    css: slides.css
fig-cap-location: top
slide-number: false
editor_options: 
  chunk_output_type: console
---


## Substance Use Treatment Barriers
- Aversion to in person therapy (stigmatized mental health issue, asking for help is hard)
- Availability (long wait times, geolocation barriers)
- Affordability

::: aside
x in x people do not receive treatment for a substance use disorder.
:::

## Gaps in Current Treatment
- Time-limited
- Interventions limited to therapy schedule
- Expects clients to recognize their risk of return to use

## Digital Therapeutics With Personal Sensing
- Describe
- Potential for Mitigating Barriers to Treatment


## Some Questions we First Need Answered
1. Will people find collection of these personally sensed data acceptable?
2. Can we predict risk of return to substance use with clinically useful accuracy?
3. Can we predict risk of return to substance use with clinically useful temporal precision? 

::: aside
All the while considering burden associated with long-term monitoring (what is the minimum input we need from individuals?).
:::

## Two Notes to touch on
1. *Lapse* = goal-inconsistent substance use
     - Any reported alcohol use among people who have a goal of abstinence
2. Area under the receiver operating curve (*auROC*) is our performance metric
      - Essentially measures how well our model can discriminate between a positive (lapse) and negative (no lapse) case - 0.5-1.  
      - Later we will talk about a few other metrics that are important when considering the usefulness of our models.


## Participants
- all four studies use the same data set so I am going to briefly touch on the key demographics here


# 1. Will people find collection of these personally sensed data acceptable?



## Burden Description
- Behavioral and Self-report measures of acceptability
- Separate for each personal sensing method
- All methods were being used by participants for up to three months
- Range of sensing methods (passive to active)

::: aside
Provide different methods
:::


## Behavioral Measures of Acceptability 

{{< embed ../notebooks/burden_analyses.qmd#fig-burden-compliance >}}



::: footer
Wyant et al., 2023
:::



## Self-Report Measures of Acceptability 

{{< embed ../notebooks/burden_analyses.qmd#fig-interference >}}

::: footer
Wyant et al., 2023
:::

##

{{< embed ../notebooks/burden_analyses.qmd#fig-dislike >}}

::: footer
Wyant et al., 2023
:::

##

{{< embed ../notebooks/burden_analyses.qmd#fig-willingness >}}

::: footer
Wyant et al., 2023
:::

## 5 Themes From Free-Response Comments about Acceptability

- Acceptability 
- Sustainability
- Benefits
- Trust
- Usability

::: aside
Provide examples
:::

::: footer
Wyant et al., 2023
:::


## Conclusions
- Personal sensing is acceptable among people with alcohol use disorder
- It can be used for long-term monitoring
- People may have different preferences and needs depending on the personal sensing method







::: {.notes}

:::



# 2. Can we predict risk of return to substance use with clinically useful accuracy?


## Cellular Communications

- Mostly passive personal sensing method
- Metadata gathered from phone calls and text messages
- Native text messaging and phone calls are still primary method of communication and may capture immediate (messaging someone risky to sobriety) and slower acting (changes in social circle) factors related to risk.


## Cellular Communications for Predicting Next Hour Lapses back to Alcohol Use

{{< embed ../notebooks/fyp_analyses.qmd#fig-fyp-posteriors >}}

*Annotate with Mean and CI values*

::: footer
Wyant & Curtin, *First Year Project*
:::

::: {.notes}

10x10 1 hour (1x10 fit on chtc for model selection)

Best configuration from model selection (validaiton) = random_forest, passive feats, hp1 = 50, hp2 = 2, hp3 = 10000, resample = up_1, feature_fun_type = "perc", roc_auc = .69, 122 features retained


10x10 fits - mean roc_auc = .64 (mean posterior = )

:::

## Model Contrast

{{< embed ../notebooks/fyp_analyses.qmd#fig-fyp-contrasts >}}


::: footer
Wyant & Curtin, *First Year Project*
:::


## Conclusion

- Cellular communications can detect lapse risk signal...
- but not with high enough performance to be implemented clinically on its own.



## Ecological Momentary Assessment (EMA)

- Active sensing method (4x daily) 
- Face valid constructs related to extant relapse prevention literature
- Also decided to extend beyond next hour predictions and look at prediction windows of next week, next day, and next hour



## EMA for Predicting Next Week, Day, and Hour Lapses back to Alcohol Use

{{< embed ../notebooks/ema_analyses.qmd#fig-ema-posteriors >}}


*Annotate with mean and CI values*


::: footer
Wyant & Sant'Ana et al., *in press*
:::

## Model Contrasts

{{< embed ../notebooks/ema_analyses.qmd#fig-ema-contrasts >}}

::: footer
Wyant & Sant'Ana et al., *in press*
:::


::: {.notes}


:::

## Table of performance metrics across models
- unpack PPV


## Relative Top Features
- Global SHAP bar plot
- Mention variance among observations but dont show sina plot
- Discuss top predictor as previous lapses and introduce baseline comparison (high vs. low lapser)

::: footer
Wyant & Sant'Ana et al., *in press*
:::

## Baseline Model Contrasts

{{< embed ../notebooks/ema_analyses.qmd#fig-ema-baseline >}}


::: footer
Wyant & Sant'Ana et al., *in press*
:::

## Conclusions
EMA can be used to predict lapses back to alcohol use    

- with high sensitivity and specificity
- varying positive predictive value



# 3. Can we predict risk of return to substance use with clinically useful temporal precision? 


## Lag Study 

- we have demonstrated we can predict lapses back to alcohol use from EMA data with high accuracy for next hour, next day, and next week.
- Introduce idea of lagged predictions for making week models more useful (higher PPV, have time to implement intervention).


## Lagged Predictions of Next Week Alcohol Lapses 


{{< embed ../notebooks/lag_analyses.qmd#fig-lag-posteriors >}}

::: footer
Wyant et al., *in prep* 
:::

## Model Contrasts

{{< embed ../notebooks/lag_analyses.qmd#fig-lag-contrasts >}}

::: footer
Wyant et al., *in prep*
:::

## Conclusion

## Future Directions
- opioid use disorder (extending beyond alcohol use)
- combining active and passive methods
- non-abstinent and other harm reduction outcomes 

## Acknowledgments 
