---
title: EMA Analyses
author: Kendra Wyant
editor_options: 
  chunk_output_type: console
---

```{r}
#|echo: FALSE

# handle conflicts
options(conflicts.policy = "depends.ok")
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/fun_ml.R?raw=true")
tidymodels_conflictRules()

library(tidyverse)
library(tidymodels)
library(tidyposterior)
library(ggtext)
library(patchwork)
theme_set(theme_classic())

devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")
```

### Compliance

```{r}
path_shared <- format_path("studydata/risk/data_processed/shared")
path_ema<- format_path("studydata/risk/data_processed/ema")


visit_dates <- read_csv(file.path(path_shared, "visit_dates.csv"), col_types = cols())
ema_m <- vroom::vroom(file.path(path_shared, "ema_morning.csv"), col_types = vroom::cols()) %>% 
  mutate(start_date = with_tz(start_date, tzone = "America/Chicago"),
         subid = as.numeric(subid))
ema_l <- vroom::vroom(file.path(path_shared, "ema_later.csv"), col_types = vroom::cols()) %>% 
  mutate(start_date = with_tz(start_date, tzone = "America/Chicago"),
         subid = as.numeric(subid))
```

```{r}
disposition <- read_csv(file.path(path_ema, "disposition.csv"), col_types = cols())

# function to map over
get_study_days <- function(the_subid, dates) {
  start_study <- dates %>% filter(subid == the_subid) %>% pull(start_study)
  end_study <- dates %>% filter(subid == the_subid) %>% pull(end_study)
  study_days <- tibble(subid = the_subid, study_day = seq(start_study, end_study - days(1), by = "day")) 
  return(study_days)
}

sample <- disposition %>% 
  filter(analysis == "yes")

subids <- sample$subid
dates <- sample %>% 
  select(subid, start_study, end_study)

study_dates <- subids %>% 
  map_dfr(~get_study_days(.x, dates))
```






```{r}
ema <- ema_m |> 
  select(subid, start_date) |> 
  full_join(ema_l |> select(subid, start_date), by = c("subid", "start_date")) |> 
  mutate(start_date = date(start_date)) |> 
  filter(subid %in% subids)

# count EMAs per day
ema_count_4x <- ema |>  
  count(subid, start_date) |>
  mutate(n = if_else(n > 4, 4, as.numeric(n)))

# left join with study dates
ema_study_dates <- study_dates |>
  left_join(ema_count_4x, by = c("subid", "study_day" = "start_date")) |> 
  mutate(n = if_else(is.na(n), 0, n)) |> 
  mutate(n_prompts = 4)

# slice into 7 day bins
ema_study_weeks <- ema_study_dates |> 
  group_by(subid) |> 
  slice(1:7) |> 
  mutate(week = 1) |> 
  bind_rows(ema_study_dates |> 
    group_by(subid) |> 
    slice(8:14) |> 
    mutate(week = 2)) |> 
  bind_rows(ema_study_dates |> 
    group_by(subid) |> 
    slice(15:21) |> 
    mutate(week = 3)) |> 
  bind_rows(ema_study_dates |> 
    group_by(subid) |> 
    slice(22:28) |> 
    mutate(week = 4)) |> 
  bind_rows(ema_study_dates |> 
    group_by(subid) |> 
    slice(29:35) |> 
    mutate(week = 5)) |> 
  bind_rows(ema_study_dates |> 
    group_by(subid) |> 
    slice(36:42) |> 
    mutate(week = 6)) |> 
  bind_rows(ema_study_dates |> 
    group_by(subid) |> 
    slice(43:49) |> 
    mutate(week = 7)) |> 
  bind_rows(ema_study_dates |> 
    group_by(subid) |> 
    slice(50:56) |> 
    mutate(week = 8)) |> 
  bind_rows(ema_study_dates |> 
    group_by(subid) |> 
    slice(57:63) |> 
    mutate(week = 9)) |> 
  bind_rows(ema_study_dates |> 
    group_by(subid) |> 
    slice(64:70) |> 
    mutate(week = 10)) |> 
  bind_rows(ema_study_dates |> 
    group_by(subid) |> 
    slice(71:77) |> 
    mutate(week = 11)) |> 
  bind_rows(ema_study_dates |> 
    group_by(subid) |> 
    slice(78:84) |> 
    mutate(week = 12)) |> 
  ungroup()

ema_week_compliance_4x <- ema_study_weeks |> 
  group_by(subid, week) |> 
  summarize(sum_n = sum(n), sum_prompts = sum(n_prompts), .groups = "rowwise") |> 
  mutate(compliance = sum_n/sum_prompts) |> 
  ungroup()

ema_week_compliance_1x <- ema_study_weeks |>
  mutate(n = if_else(n > 1, 1, n),
         n_prompts = 1) |> 
  group_by(subid, week) |> 
  summarize(sum_n = sum(n), sum_prompts = sum(n_prompts), .groups = "rowwise") |> 
  mutate(compliance = sum_n/sum_prompts) |> 
  ungroup()

week_compliance_all <- ema_week_compliance_4x |> 
              mutate(compliance = compliance*100) |> 
              group_by(week) |> 
              summarize(mean_compliance = mean(compliance),
                        n = n(),
                        sd = sd(compliance)) |> 
              mutate(se = sd/sqrt(n),
                     signal = "4x Daily") |> 
  bind_rows(ema_week_compliance_1x |> 
              mutate(compliance = compliance*100) |> 
              group_by(week) |> 
              summarize(mean_compliance = mean(compliance),
                        n = n(),
                        sd = sd(compliance)) |> 
              mutate(se = sd/sqrt(n),
                     signal = "1x Daily")) 
```


```{r}
#| label: fig-burden-compliance

week_compliance_all |> 
  group_by(week, signal) |> 
  ggplot(aes(x = week, y = mean_compliance, group = signal, color = signal, fill = signal)) +
  geom_line() +
  geom_ribbon(aes(ymin = mean_compliance - se, ymax = mean_compliance + se), alpha = .4) +
  theme_classic() +
  scale_color_manual(values = c("#4A235A", "#0B5345")) +
  scale_fill_manual(values = c("#D7BDE2", "#A2D9CE")) +
  scale_x_continuous(name = "Week", 
                     breaks = seq(1, 12, 1)) +
  scale_y_continuous(name = "Completion percentage", 
                     breaks = seq(0, 100, 10), 
                     limits = c(0, 100)) +
  geom_hline(aes(yintercept = mean_compliance, color = signal), week_compliance_all |> 
               group_by(signal) |> 
               summarize(mean_compliance = mean(mean_compliance)),
             linetype = "dashed", linewidth = .3) +
  theme(legend.title = element_blank(),
        legend.position = "bottom") 
```

### Acceptability Figures
```{r}
path_burden <- "P:/studydata/risk/data_processed/burden"
```

```{r}
data <- read_csv(file.path(path_burden, "acceptability.csv"), col_types = cols()) %>% 
  # wristband will be analyzed in supplemental - not enough observations
  select(-contains("wristband"))
```

Pull out last observation for each participant
```{r}
# pull out last available sleep monitor data since this date will be earlier than last 
# survey date for some due to discontinuation of monitor
data_sleep <- data %>% 
  filter(!is.na(sleep_interfere)) %>% 
  group_by(subid) %>% 
  arrange(desc(date)) %>% 
  slice(1) %>% 
  ungroup() %>% 
  select(c(subid, starts_with("sleep_")))
  
# pull out most recent survey for each subid
data_last <- data %>% 
  select(-c(starts_with("sleep_"))) %>% 
  group_by(subid) %>% 
  arrange(desc(date)) %>% 
  slice(1) %>% 
  ungroup() %>% 
  # join with sleep data
  full_join(data_sleep, by = c("subid")) %>% 
  glimpse()
```

ema



```{r}
plot_1 <- data_last |> 
  select(Interference = daily_survey_interfere,
         Dislike = daily_survey_dislike) |> 
  pivot_longer(everything(), names_to = "measure") |> 
  mutate(measure = factor(measure, 
                          levels = c("Interference", "Dislike")),
         value = factor(value, levels = c(-2:2), 
                        labels = c("Strongly agree", "Agree", "Undecided", "Disagree", "Strongly disagree"))) |> 
  ggplot(aes(x = value, y = ..prop.., group = measure, color = measure, fill = measure)) +
  geom_bar() +
  scale_color_manual(values = c("#0B5345", "#0B5345")) +
  scale_fill_manual(values = c("#A2D9CE", "#A2D9CE")) +
  facet_grid(~measure) +
  theme_classic() +
  labs(y = "Proportion",
       x = NULL) +
  theme(legend.position = "none",
        text = element_text(size = 12),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylim(0, .6) +
  geom_vline(aes(xintercept = "Undecided"), linetype = "dashed", size = .4, color = "black") +
  geom_vline(aes(xintercept = means, color = measure), data_last |> 
  select(Interference = daily_survey_interfere,
         Dislike = daily_survey_dislike) |> 
  pivot_longer(everything(), names_to = "measure") |> 
  mutate(measure = factor(measure, 
                          levels = c("Interference", "Dislike")),
         value = factor(value, levels = c(-2:2), 
                        labels = c("Strongly agree", "Agree", "Undecided", "Disagree", "Strongly disagree"))) |> 
  group_by(measure) |> 
  summarise(means = mean(as.numeric(value), na.rm = TRUE)), size = .705) 


# plot_2 <- data_last |>
#   select(`Willingness (4x)`= daily_survey_4_1year,
#          `Willingness (1x)`= daily_survey_1_1year) |>
#   pivot_longer(everything(), names_to = "measure") |>
#   mutate(measure = factor(measure,
#                           levels = c("Willingness (4x)", "Willingness (1x)")),
#          value = factor(value, levels = c(-2:2),
#                         labels = c("Strongly disagree", "Disagree", "Undecided", "Agree", "Strongly Agree"))) |>
#   ggplot(aes(x = value, y = ..prop.., group = measure, color = measure, fill = measure)) +
#   geom_bar() +
#   scale_color_manual(values = c("#0B5345", "#4A235A")) +
#   scale_fill_manual(values = c("#A2D9CE", "#D7BDE2")) +
#   facet_grid(~measure) +
#   theme_classic() +
#   labs(y = "Proportion",
#        x = NULL) +
#   theme(legend.position = "none",
#         text = element_text(size = 12),
#         axis.text.x = element_text(angle = 45, hjust = 1)) +
#   ylim(0, .6) +
#   geom_vline(aes(xintercept = "Undecided"), linetype = "dashed", size = .4, color = "black") +
#   geom_vline(aes(xintercept = means, color = measure), data_last |>
#   select(`Willingness (4x)` = daily_survey_4_1year,
#          `Willingness (1x)` = daily_survey_1_1year) |>
#   pivot_longer(everything(), names_to = "measure") |>
#   mutate(measure = factor(measure,
#                           levels = c("Willingness (4x)", "Willingness (1x)")),
#          value = factor(value, levels = c(-2:2),
#                         labels = c("Strongly disagree", "Disagree", "Undecided", "Agree", "Strongly Agree"))) |>
#   group_by(measure) |>
#   summarise(means = mean(as.numeric(value), na.rm = TRUE)), size = .705)  +
#   theme(axis.title.y = element_blank(),
#         axis.line.y = element_blank(),
#         axis.text.y = element_blank(),
#         axis.ticks.y = element_blank())

plot_2 <- data_last |>
  select(`Willingness`= daily_survey_4_1year,) |>
  pivot_longer(everything(), names_to = "measure") |>
  mutate(measure = factor(measure,
                          levels = c("Willingness")),
         value = factor(value, levels = c(-2:2),
                        labels = c("Strongly disagree", "Disagree", "Undecided", "Agree", "Strongly Agree"))) |>
  ggplot(aes(x = value, y = ..prop.., group = measure, color = measure, fill = measure)) +
  geom_bar() +
  scale_color_manual(values = c("#0B5345")) +
  scale_fill_manual(values = c("#A2D9CE")) +
  facet_grid(~measure) +
  theme_classic() +
  labs(y = "Proportion",
       x = NULL) +
  theme(legend.position = "none",
        text = element_text(size = 12),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylim(0, .6) +
  geom_vline(aes(xintercept = "Undecided"), linetype = "dashed", size = .4, color = "black") +
  geom_vline(aes(xintercept = means, color = measure), data_last |>
  select(`Willingness` = daily_survey_4_1year) |>
  pivot_longer(everything(), names_to = "measure") |>
  mutate(measure = factor(measure,
                          levels = c("Willingness")),
         value = factor(value, levels = c(-2:2),
                        labels = c("Strongly disagree", "Disagree", "Undecided", "Agree", "Strongly Agree"))) |>
  group_by(measure) |>
  summarise(means = mean(as.numeric(value), na.rm = TRUE)), size = .705)  +
  theme(axis.title.y = element_blank(),
        axis.line.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())

plot_1 + plot_2 + 
  plot_layout(width = c(1,.5))
```

```{r}
data_last |>
  select(`Willingness (1x EMA)`= daily_survey_1_1year,) |>
  pivot_longer(everything(), names_to = "measure") |>
  mutate(measure = factor(measure,
                          levels = c("Willingness (1x EMA)")),
         value = factor(value, levels = c(-2:2),
                        labels = c("Strongly disagree", "Disagree", "Undecided", "Agree", "Strongly Agree"))) |>
  ggplot(aes(x = value, y = ..prop.., group = measure, color = measure, fill = measure)) +
  geom_bar() +
  scale_color_manual(values = c("#4A235A")) +
  scale_fill_manual(values = c("#D7BDE2")) +
  facet_grid(~measure) +
  theme_classic() +
  labs(y = "Proportion",
       x = NULL) +
  theme(legend.position = "none",
        text = element_text(size = 12),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylim(0, .6) +
  geom_vline(aes(xintercept = "Undecided"), linetype = "dashed", size = .4, color = "black") +
  geom_vline(aes(xintercept = means, color = measure), data_last |>
  select(`Willingness (1x EMA)` = daily_survey_1_1year) |>
  pivot_longer(everything(), names_to = "measure") |>
  mutate(measure = factor(measure,
                          levels = c("Willingness (1x EMA)")),
         value = factor(value, levels = c(-2:2),
                        labels = c("Strongly disagree", "Disagree", "Undecided", "Agree", "Strongly Agree"))) |>
  group_by(measure) |>
  summarise(means = mean(as.numeric(value), na.rm = TRUE)), size = .705)  
```


gps
```{r}
plot_1 <- data_last |> 
  select(Dislike = location_dislike) |> 
  pivot_longer(everything(), names_to = "measure") |> 
  mutate(measure = factor(measure, 
                          levels = c("Interference", "Dislike")),
         value = factor(value, levels = c(-2:2), 
                        labels = c("Strongly agree", "Agree", "Undecided", "Disagree", "Strongly disagree"))) |> 
  ggplot(aes(x = value, y = ..prop.., group = measure, color = measure, fill = measure)) +
  geom_bar() +
  scale_color_manual(values = c("#0B5345")) +
  scale_fill_manual(values = c("#A2D9CE")) +
  facet_grid(~measure) +
  theme_classic() +
  labs(y = "Proportion",
       x = NULL) +
  theme(legend.position = "none",
        text = element_text(size = 12),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylim(0, .6) +
  geom_vline(aes(xintercept = "Undecided"), linetype = "dashed", size = .4, color = "black") +
  geom_vline(aes(xintercept = means, color = measure), data_last |> 
  select(Dislike = location_dislike) |> 
  pivot_longer(everything(), names_to = "measure") |> 
  mutate(measure = factor(measure, 
                          levels = c("Interference", "Dislike")),
         value = factor(value, levels = c(-2:2), 
                        labels = c("Strongly agree", "Agree", "Undecided", "Disagree", "Strongly disagree"))) |> 
  group_by(measure) |> 
  summarise(means = mean(as.numeric(value), na.rm = TRUE)), size = .705) 


plot_2 <- data_last |> 
  select(`Willingness`= location_1year) |> 
  pivot_longer(everything(), names_to = "measure") |> 
  mutate(measure = factor(measure, 
                          levels = c("Willingness")),
         value = factor(value, levels = c(-2:2), 
                        labels = c("Strongly disagree", "Disagree", "Undecided", "Agree", "Strongly Agree"))) |> 
  ggplot(aes(x = value, y = ..prop.., group = measure, color = measure, fill = measure)) +
  geom_bar() +
  scale_color_manual(values = c("#0B5345")) +
  scale_fill_manual(values = c("#A2D9CE")) +
  facet_grid(~measure) +
  theme_classic() +
  labs(y = "Proportion",
       x = NULL) +
  theme(legend.position = "none",
        text = element_text(size = 12),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylim(0, .6) +
  geom_vline(aes(xintercept = "Undecided"), linetype = "dashed", size = .4, color = "black") +
  geom_vline(aes(xintercept = means, color = measure), data_last |> 
  select(`Willingness` = location_1year) |> 
  pivot_longer(everything(), names_to = "measure") |> 
  mutate(measure = factor(measure, 
                          levels = c("Willingness")),
         value = factor(value, levels = c(-2:2), 
                        labels = c("Strongly disagree", "Disagree", "Undecided", "Agree", "Strongly Agree"))) |> 
  group_by(measure) |> 
  summarise(means = mean(as.numeric(value), na.rm = TRUE)), size = .705)  +
  theme(axis.title.y = element_blank(),
        axis.line.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())

plot_1 + plot_2 
```

cellular communications
```{r}
plot_1 <- data_last |> 
  select(Dislike = all_logs_dislike) |> 
  pivot_longer(everything(), names_to = "measure") |> 
  mutate(measure = factor(measure, 
                          levels = c("Dislike")),
         value = factor(value, levels = c(-2:2), 
                        labels = c("Strongly agree", "Agree", "Undecided", "Disagree", "Strongly disagree")),
         sensing = "Metadata") |> 
  ggplot(aes(x = value, y = ..prop.., group = measure, color = measure, fill = measure)) +
  geom_bar() +
  scale_color_manual(values = c("#0B5345")) +
  scale_fill_manual(values = c("#A2D9CE")) +
  facet_grid(~measure) +
  theme_classic() +
  labs(y = "Proportion",
       x = NULL) +
  theme(legend.position = "none",
        text = element_text(size = 12),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylim(0, .6) +
  geom_vline(aes(xintercept = "Undecided"), linetype = "dashed", size = .4, color = "black") +
  geom_vline(aes(xintercept = means, color = measure), data_last |> 
  select(Dislike = all_logs_dislike) |> 
  pivot_longer(everything(), names_to = "measure") |> 
  mutate(measure = factor(measure, 
                          levels = c("Interference", "Dislike")),
         value = factor(value, levels = c(-2:2), 
                        labels = c("Strongly agree", "Agree", "Undecided", "Disagree", "Strongly disagree")),
         sensing = "Metadata") |> 
  group_by(measure) |> 
  summarise(means = mean(as.numeric(value), na.rm = TRUE)), size = .705) +
  theme(axis.ticks.x = element_blank(),
        axis.text.x = element_blank())


plot_2 <- data_last |> 
  select(`Willingness`= all_logs_1year) |> 
  pivot_longer(everything(), names_to = "measure") |> 
  mutate(measure = factor(measure, 
                          levels = c("Willingness")),
         value = factor(value, levels = c(-2:2), 
                        labels = c("Strongly disagree", "Disagree", "Undecided", "Agree", "Strongly Agree")),
         sensing = "Metadata") |> 
  ggplot(aes(x = value, y = ..prop.., group = measure, color = measure, fill = measure)) +
  geom_bar() +
  scale_color_manual(values = c("#0B5345")) +
  scale_fill_manual(values = c("#A2D9CE")) +
  facet_grid(sensing~measure) +
  theme_classic() +
  labs(y = "Proportion",
       x = NULL) +
  theme(legend.position = "none",
        text = element_text(size = 12),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylim(0, .6) +
  geom_vline(aes(xintercept = "Undecided"), linetype = "dashed", size = .4, color = "black") +
  geom_vline(aes(xintercept = means, color = measure), data_last |> 
  select(`Willingness` = all_logs_1year) |> 
  pivot_longer(everything(), names_to = "measure") |> 
  mutate(measure = factor(measure, 
                          levels = c("Willingness")),
         value = factor(value, levels = c(-2:2), 
                        labels = c("Strongly disagree", "Disagree", "Undecided", "Agree", "Strongly Agree")),
         sensing = "Metadata") |> 
  group_by(measure) |> 
  summarise(means = mean(as.numeric(value), na.rm = TRUE)), size = .705)  +
  theme(axis.title = element_blank(),
        axis.line.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_blank())

plot_3 <- data_last |> 
  select(Dislike = sms_content_dislike) |> 
  pivot_longer(everything(), names_to = "measure") |> 
  mutate(measure = factor(measure, 
                          levels = c("Dislike")),
         value = factor(value, levels = c(-2:2), 
                        labels = c("Strongly agree", "Agree", "Undecided", "Disagree", "Strongly disagree")),
         sensing = "SMS Content") |> 
  ggplot(aes(x = value, y = ..prop.., group = measure, color = measure, fill = measure)) +
  geom_bar() +
   scale_color_manual(values = c("#0B5345")) +
  scale_fill_manual(values = c("#A2D9CE")) +
  facet_grid(~measure) +
  theme_classic() +
  labs(y = "Proportion",
       x = NULL) +
  theme(legend.position = "none",
        text = element_text(size = 12),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylim(0, .6) +
  geom_vline(aes(xintercept = "Undecided"), linetype = "dashed", size = .4, color = "black") +
  geom_vline(aes(xintercept = means, color = measure), data_last |> 
  select(Dislike = sms_content_dislike) |> 
  pivot_longer(everything(), names_to = "measure") |> 
  mutate(measure = factor(measure, 
                          levels = c("Dislike")),
         value = factor(value, levels = c(-2:2), 
                        labels = c("Strongly agree", "Agree", "Undecided", "Disagree", "Strongly disagree")),
         sensing = "SMS Content") |> 
  group_by(measure) |> 
  summarise(means = mean(as.numeric(value), na.rm = TRUE)), size = .705) 


plot_4 <- data_last |> 
  select(`Willingness`= sms_content_1year) |> 
  pivot_longer(everything(), names_to = "measure") |> 
  mutate(measure = factor(measure, 
                          levels = c("Willingness")),
         value = factor(value, levels = c(-2:2), 
                        labels = c("Strongly disagree", "Disagree", "Undecided", "Agree", "Strongly Agree")),
         sensing = "SMS Content") |> 
  ggplot(aes(x = value, y = ..prop.., group = measure, color = measure, fill = measure)) +
  geom_bar() +
   scale_color_manual(values = c("#0B5345")) +
  scale_fill_manual(values = c("#A2D9CE")) +
  facet_grid(sensing~measure) +
  theme_classic() +
  labs(y = "Proportion",
       x = NULL) +
  theme(legend.position = "none",
        text = element_text(size = 12),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylim(0, .6) +
  geom_vline(aes(xintercept = "Undecided"), linetype = "dashed", size = .4, color = "black") +
  geom_vline(aes(xintercept = means, color = measure), data_last |> 
  select(`Willingness` = sms_content_1year) |> 
  pivot_longer(everything(), names_to = "measure") |> 
  mutate(measure = factor(measure, 
                          levels = c("Willingness")),
         value = factor(value, levels = c(-2:2), 
                        labels = c("Strongly disagree", "Disagree", "Undecided", "Agree", "Strongly Agree")),
         sensing = "SMS Content") |> 
  group_by(measure) |> 
  summarise(means = mean(as.numeric(value), na.rm = TRUE)), size = .705)  +
  theme(axis.title = element_blank(),
        axis.line.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())

(plot_1 + plot_2) / (plot_3 + plot_4)
```

```{r}
#| label: fig-interference
#| fig-cap: "[personal sensing method] interfered with my daily activities"

interference_plot_data <- data_last %>% 
  select(contains("interfere"), -carrying_phone_interfere) %>%   
  pivot_longer(everything(), names_to = "measure", values_drop_na = TRUE) %>% 
  mutate(measure = factor(measure, 
                          levels = c("audio_checkin_interfere", "daily_survey_interfere", 
                                     "sleep_interfere"),
                          labels = c("Audio check-in", "EMA", "Sleep quality"))) %>% 
  mutate(value = factor(value, levels = c(-2:2), labels = c("Strongly agree", "Agree", "Undecided", "Disagree", "Strongly disagree"))) %>% 
  mutate(active = case_when(measure == "Audio check-in" ~ "Active methods",
                            measure == "EMA" ~ "Active methods",
                            measure == "Sleep quality" ~ "Active methods")) 

interference_plot <- interference_plot_data %>% 
  filter(measure == "Audio check-in" | measure == "EMA" | measure == "Sleep quality") %>% 
  ggplot(aes(x = value, y = ..prop.., group = measure)) +
  geom_bar(color = "black", fill = "#FFDEDE") +
  facet_grid(active ~ measure) +
  theme_classic() +
  labs(y = "Proportion",
       x = NULL) +
  theme(legend.position = "none",
        text = element_text(size = 12),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylim(0, .6) +
  geom_vline(aes(xintercept = "Undecided"), linetype = "dashed", size = .4, color = "#787575") +
  geom_vline(aes(xintercept = means), interference_plot_data %>% 
  filter(measure == "Audio check-in" | measure == "EMA" | measure == "Sleep quality") %>% 
  group_by(measure) %>% 
  summarise(means = mean(as.numeric(value), na.rm = TRUE)), size = .705, color = "#b44343") 


interference_plot
```

```{r}
#| label: fig-dislike
#| fig-cap: "I disliked [personal sensing method]"

dislike_plot_data <- data_last %>% 
  select(contains("dislike")) %>%  
  pivot_longer(everything(), names_to = "measure", values_drop_na = TRUE) %>% 
   mutate(measure = factor(measure, 
                          levels = c("audio_checkin_dislike", "daily_survey_dislike", "sleep_dislike",
                                     "location_dislike", "all_logs_dislike", "sms_content_dislike"),
                          labels = c("Audio check-in", "EMA", "Sleep quality",
                                     "Geolocation", "Cellular communication logs", "SMS text message content"))) %>% 
  mutate(value = factor(value, levels = c(-2:2), labels = c("Strongly agree", "Agree", "Undecided", "Disagree", "Strongly disagree"))) %>% 
  mutate(active = case_when(measure == "Audio check-in" ~ "Active methods",
                            measure == "EMA" ~ "Active methods",
                            measure == "Sleep quality" ~ "Active methods",
                            measure == "Geolocation" ~ "Passive methods",
                            measure == "Cellular communication logs" ~ "Passive methods",
                            measure == "SMS text message content" ~ "Passive methods")) 

active_dis <- dislike_plot_data %>% 
  filter(measure == "Audio check-in" | measure == "EMA" | measure == "Sleep quality") %>% 
  ggplot(aes(x = value, y = ..prop.., group = measure)) +
  geom_bar(color = "black", fill = "#FFDEDE") +
  facet_grid(active ~ measure) +
  theme_classic() +
  labs(y = NULL,
       x = NULL) +
  theme(legend.position = "none",
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        text = element_text(size = 12)) +
  ylim(0, .65) +
  geom_vline(aes(xintercept = means), dislike_plot_data %>% 
  filter(measure == "Audio check-in" | measure == "EMA" | measure == "Sleep quality") %>% 
  group_by(measure) %>% 
  summarise(means = mean(as.numeric(value), na.rm = TRUE)), size = .705, color = "#b44343") +
  geom_vline(aes(xintercept = "Undecided"), linetype = "dashed", size = .4, color = "#787575") +
  theme(text = element_text(size = 12))


passive_dis <- dislike_plot_data %>% 
  filter(measure == "Geolocation" | measure == "Cellular communication logs" | measure == "SMS text message content") %>% 
  ggplot(aes(x = value, y = ..prop.., group = measure)) +
  geom_bar(color = "black", fill = "#DBF8FF") +
  facet_grid(active ~ measure) +
  theme_classic() +
  labs(y = NULL,
       x = NULL) +
    theme(legend.position = "none",
        text = element_text(size = 12),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylim(0, .6) +
  geom_vline(aes(xintercept = means), dislike_plot_data %>% 
  filter(measure == "Geolocation" | measure == "Cellular communication logs" | measure == "SMS text message content") %>%  
  group_by(measure) %>% 
  summarise(means = mean(as.numeric(value), na.rm = TRUE)), size = .705, color = "#05667b") +
  geom_vline(aes(xintercept = "Undecided"), linetype = "dashed", size = .4, color = "#787575") 

dislike_plot <- wrap_plots(active_dis, passive_dis, ncol = 1)

dislike_plot <- dislike_plot  %>% 
  add_global_label(Ylab = "                   Proportion",
                   Ygap = .02
)

dislike_plot
```

```{r}
#| label: fig-willingness
#| fig-cap: "I would be willing to use [personal sensing method] for one year to help with my recovery"

willingness_plot_data <- data_last %>% 
  select(contains("1year")) %>%  
  pivot_longer(everything(), names_to = "measure", values_drop_na = TRUE) %>% 
  mutate(measure = factor(measure, 
                          levels = c("audio_checkin_1year", "daily_survey_4_1year", 
                                     "daily_survey_1_1year", "sleep_1year", "location_1year", 
                                     "all_logs_1year", "sms_content_1year"),
                          labels = c("Audio check-in", "EMA", "Daily Survey (x1)<i><sup>a</sup></i>",
                                     "Sleep quality", "Geolocation", "Cellular communication logs", 
                                     "SMS text message content"))) %>% 
  mutate(value = factor(value, levels = c(-2:2), labels = c("Strongly disagree", "Disagree", "Undecided", "Agree", "Strongly agree"))) %>% 
  mutate(active = case_when(measure == "Audio check-in" ~ "Active methods",
                            measure == "EMA" ~ "Active methods",
                            measure == "Sleep quality" ~ "Active methods",
                            measure == "Geolocation" ~ "Passive methods",
                            measure == "Cellular communication logs" ~ "Passive methods",
                            measure == "SMS text message content" ~ "Passive methods")) 

willingness_active <- willingness_plot_data %>% 
  filter(measure == "Audio check-in" | measure == "EMA" | measure == "Sleep quality") %>% 
  ggplot(aes(x = value, y = ..prop.., group = measure)) +
  geom_bar(color = "black", fill = "#FFDEDE") +
  facet_grid(active ~ measure) +
  theme_classic() +
  labs(y = NULL,
       x = NULL) +
  theme(legend.position = "none",
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        text = element_text(size = 12),
        strip.text = element_markdown()) +
  ylim(0, .6) +
  geom_vline(aes(xintercept = means), willingness_plot_data %>% 
  filter(measure == "Audio check-in" | measure == "EMA" | measure == "Sleep quality") %>% 
  group_by(measure) %>% 
  summarise(means = mean(as.numeric(value), na.rm = TRUE)), size = .705, color = "#b44343") +
  geom_vline(aes(xintercept = "Undecided"), linetype = "dashed", size = .4, color = "#787575")


willingness_passive <- willingness_plot_data %>% 
  filter(measure == "Geolocation" | measure == "Cellular communication logs" | measure == "SMS text message content") %>% 
  ggplot(aes(x = value, y = ..prop.., group = measure)) +
  geom_bar(color = "black", fill = "#DBF8FF") +
  facet_grid(active ~ measure) +
  theme_classic() +
  labs(y = NULL,
       x = NULL) +
    theme(legend.position = "none",
        text = element_text(size = 12),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylim(0, .6) +
  geom_vline(aes(xintercept = means), willingness_plot_data %>% 
  filter(measure == "Geolocation" | measure == "Cellular communication logs" | measure == "SMS text message content") %>%  
  group_by(measure) %>% 
  summarise(means = mean(as.numeric(value), na.rm = TRUE)), size = .705, color = "#05667b") +
  geom_vline(aes(xintercept = "Undecided"), linetype = "dashed", size = .4, color = "#787575")

willingness_final_plot <- wrap_plots(willingness_active, willingness_passive, ncol = 1)

willingness_final_plot <- willingness_final_plot  %>% 
  add_global_label(Ylab = "                   Proportion",
                   Ygap = .02
)

willingness_final_plot
```




