---
title: "EMA demographics fig"
author: "John Curtin and Kendra Wyant"
editor_options: 
  chunk_output_type: console
---

## Overview and Setup

Creates a paneled figure for EMA study demograhics

### Set up environment
```{r}
# handle conflicts
options(conflicts.policy = "depends.ok")

library(tidyverse)
theme_set(theme_classic()) 

# Paths
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true",
                     sha1 = "d5d4cd8e60c50328ca66795beb9d1f8c08b92803")
# source("../../lab_support/format_path.R")
path_processed <- "/Volumes/private/studydata/risk/data_processed/ema"
path_shared <- "/Volumes/private/studydata/risk/data_processed/shared"
```


### Read in data

```{r}
disposition <- read_csv(file.path(path_processed, "disposition.csv"), 
                        col_types = "ccDDcccccccccc")
screen <- read_csv(file.path(path_shared, "screen.csv"), 
                   col_types = cols()) |>
  filter(subid %in% subset(disposition, analysis == "yes")$subid) |> 
  mutate(across(dsm5_1:dsm5_11, ~ if_else(.x == "Yes", 1, 0))) |>  
  rowwise() |>  
  mutate(aud_total = sum(c(dsm5_1, dsm5_2, dsm5_3, dsm5_4, dsm5_5, dsm5_6, dsm5_7, 
                              dsm5_8, dsm5_9, dsm5_10, dsm5_11))) |> 
  ungroup() |> 
  select(age = dem_1, sex = dem_2, race = dem_3, ethnicity = dem_4, educ = dem_5, 
         income = dem_7, ms = dem_8, aud_total)  |> 
    mutate(educ = case_match(educ, 
                  "2-Year degree" ~ "Some college",
                  "High school or GED" ~ "<= High school", 
                  "Less than high school or GED degree" ~ "<= High school",
                  "College degree" ~ "4 year degree",
                  .default = educ)) 
```

## Pie Charts

Education

```{r}
fig_educ <- screen |>
  mutate(group = educ) |> 
  mutate(group = fct(group, levels = c(
    "<= High school", "Some college",
    "4 year degree", "Advanced degree"
  ))) |>
  ggplot(aes(x = group), fill = "#263238") +
  geom_bar(stat = "count") +
  ggtitle(NULL) +
  xlab(NULL) +
  theme(text = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(angle = 45, hjust = 1))
```

Race/ethnicity
```{r}
fig_race <- screen |>
  ggplot(aes(x = race), fill = "#263238") +
  geom_bar(stat = "count") +
  ggtitle(NULL) +
  xlab(NULL) +
  theme(plot.title = element_text(hjust = 0.5),
        text = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom")
```

Sex
```{r}
fig_sex <- screen |>
  mutate(group = sex) |> 
  ggplot(aes(x = group), fill = "#263238") +
  geom_bar(stat = "count") +
  ggtitle(NULL) +
  xlab(NULL) +
  theme(text = element_text(size = 16, face = "bold"),
        axis.text.x = element_text(angle = 45, hjust = 1))
```



## Histograms

AUD Sx

```{r}
#| label: fig-aud_symptoms 
#| fig-cap: AUD Symptom Count
#| fig-height: 6
#| fig-width: 6

fig_aud <- screen |>
  ggplot(aes(x = aud_total)) +
  geom_histogram(bins = 11, fill = "#263238", color = "white") +
  labs(title = NULL, x = "Number of AUD Symptoms", y = NULL) +
  scale_x_continuous(breaks = seq(1, 11),
                       limits = c(1, 11)) +
  theme(text = element_text(size = 16, face = "bold"),
        axis.line.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())
```

Age
```{r}
fig_age <- screen |>
  ggplot(aes(x = age)) +
  geom_histogram(fill = "#263238", color = "white", bins = 30) +
  labs(title = NULL, x = "Age", y = "Count") +
  theme(text = element_text(size = 16, face = "bold"))
```

Income

```{r}
fig_income <- screen |>
  ggplot(aes(x = income)) +
  geom_histogram(fill = "#263238", color = "white", bins = 30) +
  labs(title = NULL, x = "Income", y = NULL) +
  theme(text = element_text(size = 16, face = "bold"),
        axis.line.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())
```


## Combined 


```{r}
#| label: fig-demographics-1
#| fig-height: 5.75
#| fig-width: 12


cowplot::plot_grid(fig_race, fig_sex, fig_educ, nrow = 1, ncol = 3)

```

```{r}
#| label: fig-demographics-2
#| fig-height: 5.75
#| fig-width: 12


cowplot::plot_grid(fig_age, fig_income, fig_aud, nrow = 1, ncol = 3)

```