---
title: EMA Analyses
author: Kendra Wyant
editor_options: 
  chunk_output_type: console
---

```{r}
#|echo: FALSE

# handle conflicts
options(conflicts.policy = "depends.ok")
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/fun_ml.R?raw=true")
tidymodels_conflictRules()

library(tidyverse)
library(tidymodels)
library(tidyposterior)
theme_set(theme_classic())

devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")

path_models_lag <- format_path(str_c("studydata/risk/models/lag"))
```

### Posterior Probabilities on inner loop
```{r}
inner_lag <- read_csv(file.path(path_models_lag, 
                                 "inner_metrics_1week_0_v2_nested_main.csv"),
                       col_types = cols()) |> 
  mutate(lag = 0) |> 
  bind_rows(read_csv(file.path(path_models_lag, 
                                 "inner_metrics_1week_24_v2_nested_main.csv"),
                       col_types = cols()) |> 
  mutate(lag = 24)) |> 
  bind_rows(read_csv(file.path(path_models_lag, 
                                 "inner_metrics_1week_72_v2_nested_main.csv"),
                       col_types = cols()) |> 
  mutate(lag = 72)) |> 
  bind_rows(read_csv(file.path(path_models_lag, 
                                   "inner_metrics_1week_168_v2_nested_main.csv"),
                         col_types = cols()) |> 
  mutate(lag = 168)) |> 
  bind_rows(read_csv(file.path(path_models_lag, 
                                   "inner_metrics_1week_336_v2_nested_main.csv"),
                         col_types = cols()) |> 
  mutate(lag = 336)) |> 
  glimpse()


inner_best <- inner_lag |> 
  group_by(algorithm, feature_set, hp1, hp2, hp3, resample, lag) %>% 
    summarize(across(c(accuracy, bal_accuracy, roc_auc, sens, spec, ppv, npv),
                     median),
              n_jobs = n(), .groups = "drop") |> 
  group_by(lag) |> 
  arrange(desc(roc_auc)) |> 
  slice(1) |> 
  rename(med_roc_auc = roc_auc) |> 
  select(lag, algorithm, hp1, hp2, hp3, resample, med_roc_auc, n_jobs)

inner_lag <- inner_lag |> 
  full_join(inner_best, by = c("lag", "algorithm", "hp1", "hp2", "hp3", "resample")) |> 
  filter(!is.na(med_roc_auc))
```

```{r}
#| output: false

set.seed(101)
pp <- inner_lag |> 
  select(outer_split_num, inner_split_num, lag, roc_auc) |> 
  pivot_wider(names_from = lag, values_from = roc_auc) |> 
  rename(id = outer_split_num,
         id2 = inner_split_num) |> 
  perf_mod(formula = statistic ~ model + (1 | id2/id),
         transform = tidyposterior::logit_trans,  # for skewed & bounded AUC
         adapt_delta = .99,
         family = gaussian, 
)  
```

```{r}
pp_tidy <- pp |> 
  tidy(seed = 123) 

q = c(.025, .5, .975)
ci <- pp_tidy |> 
  group_by(model) |> 
  summarize(pp_median = quantile(posterior, probs = q[2]),
            pp_lower = quantile(posterior, probs = q[1]), 
            pp_upper = quantile(posterior, probs = q[3])) |> 
   mutate(model = factor(model, levels = c(0, 24, 72, 168, 336),
                        labels = c("0 lag", "24 lag", "72 lag", "168 lag", "336 lag")),
          y = 1000) |> 
   arrange(model)
```

```{r}
#| label: fig-lag-posteriors

pp_tidy |> 
  mutate(model = factor(model, levels = c(0, 24, 72, 168, 336),
                        labels = c("0 lag", "24 lag", "72 lag", "168 lag", "336 lag"))) |>
  ggplot() + 
  geom_histogram(aes(x = posterior), color = "#4A235A", fill = "#D7BDE2",
                 bins = 50) +
  geom_segment(mapping = aes(y = y+100, yend = y-100, x = pp_median, xend = pp_median),
               data = ci) +
  geom_segment(mapping = aes(y = y, yend = y, x = pp_lower, xend = pp_upper),
                data = ci) +
  facet_wrap(~model, ncol = 1) +
  scale_y_continuous("Posterior Probability", breaks = c(0, 500, 1000)) +
  xlab("Area Under ROC Curve") +
  theme(legend.position = "none")
```


### Model Contrasts
```{r}
# ci <- pp |>
#   contrast_models(list("0", "24", "72", "168"), 
#                   list("24", "72", "168", "336")) |> 
#   summary(size = .01) |> 
#   mutate(contrast = factor(contrast, 
#                            levels = c("0 vs 24", "24 vs 72", "72 vs 168", "168 vs 336")),
#          y = 700)
```

```{r}
#| label: fig-lag-contrasts

# pp |> 
#   tidy(seed = 123) |>   
#   group_by(model) |> 
#   mutate(sample = row_number()) |> 
#   ungroup() |> 
#   pivot_wider(names_from = model, values_from = posterior) |> 
#   mutate(`0 vs 24` = `0` - `24`,
#          `24 vs 72` = `24` - `72`,
#          `72 vs 168` = `72` - `168`,
#          `168 vs 336` = `168` - `336`) |> 
#   pivot_longer(cols = `0 vs 24`:`168 vs 336`,
#                names_to = "contrast",
#                values_to = "posterior") |> 
#   mutate(contrast = factor(contrast, 
#                            levels = c("0 vs 24", 
#                                       "24 vs 72", 
#                                       "72 vs 168",
#                                       "168 vs 336"))) |> 
#   ggplot() +
#   geom_histogram(aes(x = posterior), 
#                  color = "black", fill = "grey", 
#                  alpha = .4, bins = 30) +
#   geom_vline(xintercept = 0, linetype = "dashed") +
#   geom_segment(mapping = aes(y = y+100, yend = y-100, x = mean, xend = mean), data = ci) +
#   geom_segment(mapping = aes(y = y, yend = y, x = lower, xend = upper), data = ci) +
#   facet_wrap(~contrast, ncol = 1) +
#   ylab("Posterior Probability") +
#   xlab("Model Contrast for AUC") +
#   theme(legend.position = "none")
```